language: haskell

script:
  - cabal install --only-dependencies --enable-tests
  - echo "cabal configure --enable-tests --ghc-options=-Werror"
  - cabal install hspec
  - cabal configure --enable-tests
  - cabal build
  - cabal test
